- id: doi:10.1016/j.jdent.2021.103912
  type: paper
  description: In order to investigate the bacterial microbiome in periodontal and peri-implant biofirms from aggressive periodontitis patients, 91 plaque samples were collected and analysed using 16S rRNA gene amplification and sequencing.
  date: 2016-05-11
  image: https://onlinelibrary.wiley.com/cms/asset/d55f8b03-9d08-4eed-9bda-ba5c0dd24336/clr12834-fig-0002-m.png
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
